# Generated by Django 3.2.16 on 2024-04-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=32)),
                ('from_location_link', models.CharField(blank=True, max_length=32, null=True)),
                ('to_location_link', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event Records',
            },
        ),
        migrations.CreateModel(
            name='LocationState',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=32)),
                ('location_link', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('time_elapsed', models.IntegerField(blank=True, null=True)),
                ('inactive_time_elapsed', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(default='Active', max_length=32)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Location State Records',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=32)),
                ('location_link', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('time_elapsed', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(default='Active', max_length=32)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'State Records',
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['item_id'], name='item_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['location_link', 'item_id', 'end'], name='loc_link_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['-start', '-end'], name='timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstate',
            index=models.Index(fields=['item_id'], name='location_item_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstate',
            index=models.Index(fields=['location_link', 'item_id', 'end'], name='location_loc_link_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstate',
            index=models.Index(fields=['-start', '-end'], name='location_timestamp_idx'),
        ),
    ]
