# Generated by Django 3.2.16 on 2023-09-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=32)),
                ('location_link', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'State Records',
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['item_id'], name='item_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['location_link'], name='loc_link_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['-start', '-end'], name='timestamp_idx'),
        ),
    ]
