# Generated by Django 3.2.16 on 2023-10-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='state',
            name='loc_link_idx',
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['location_link', 'item_id', 'end'], name='loc_link_idx'),
        ),
    ]
