# Generated by Django 3.2.16 on 2023-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Event Records'},
        ),
        migrations.AddField(
            model_name='state',
            name='state',
            field=models.CharField(default='Active', max_length=32),
        ),
        migrations.AddField(
            model_name='state',
            name='time_elapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
