# Generated by Django 3.2.16 on 2024-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_event_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationState',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=32)),
                ('location_link', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('time_elapsed', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(default='Active', max_length=32)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Location State Records',
            },
        ),
        migrations.AddIndex(
            model_name='locationstate',
            index=models.Index(fields=['item_id'], name='location_item_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstate',
            index=models.Index(fields=['location_link', 'item_id', 'end'], name='location_loc_link_idx'),
        ),
        migrations.AddIndex(
            model_name='locationstate',
            index=models.Index(fields=['-start', '-end'], name='location_timestamp_idx'),
        ),
    ]
