# Generated by Django 3.2.16 on 2024-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_auto_20240124_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationstate',
            name='inactive_time_elapsed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
