# Generated by Django 3.2.16 on 2023-09-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The type of identification used e.g. barcode, RFID, Bluetooth Low Energy', max_length=30)),
                ('tag', models.CharField(help_text='Tag used to identify that this type of identifier is used e.g. "barcode", "rfid", "ble"', max_length=8, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Identifier Types',
            },
        ),
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The type of identity e.g. Product Type, Product ID, Location', max_length=30)),
                ('tag', models.CharField(help_text='A unique tag that prefixes the id string e.g. "prodtype", "prod_id", "loc"', max_length=8, unique=True)),
                ('individual', models.BooleanField(default=False, help_text='Set to true if identities of this type are individual (e.g. part id), set to false if identities of this type are collections (e.g. part type)')),
            ],
            options={
                'verbose_name_plural': 'ID Types',
            },
        ),
        migrations.CreateModel(
            name='IdentityEntry',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity_manager.identityentry')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_manager.identitytype')),
            ],
            options={
                'verbose_name_plural': 'ID Entries',
                'unique_together': {('type', 'auto_id')},
            },
        ),
        migrations.CreateModel(
            name='IdentifierPattern',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pattern', models.CharField(help_text='Regex pattern to extract details from barcode', max_length=50)),
                ('defaults', models.JSONField(help_text='default/constant identity values - used if not extracted by pattern')),
                ('label', models.CharField(help_text='label describing what this pattern is for', max_length=30)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='identity_manager.identitytype')),
                ('identifier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='identity_manager.identifiertype')),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='identity_manager.identityentry')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='identity_manager.identifiertype')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=15)),
                ('for_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_manager.identitytype')),
            ],
            options={
                'unique_together': {('key', 'for_type')},
            },
        ),
        migrations.CreateModel(
            name='ExtraFieldEntry',
            fields=[
                ('auto_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_manager.extrafield')),
                ('for_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_manager.identityentry')),
            ],
            options={
                'unique_together': {('field', 'for_entry')},
            },
        ),
    ]
